### ISSUE TITLE
Refactor genome representation

### ISSUE THREAD

**Issue by SirBob01** [SirBob01/NEAT-Python#8]
The genes are currently represented as an edge list. Refactor Genome to keep an adjacency list instead. Use topological sorting to forward propagate values.

**Comment by umair-nasir14** [comment]
Hi, I love your implementation and would like to add to this. Would you kindly elaborate on the adjacency list? Do you want to represent the genome as node and connections separately?

**Comment by SirBob01** [comment]
@umair-nasir14 I haven't worked on this code in a long time so I don't quite remember the reasons behind this issue. That said, feel free to add your own enhancements to the code. You're more than welcome to modify it as you see fit!
